# Generated by Django 3.1.5 on 2021-04-28 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('policyID', models.TextField(default='0')),
                ('dateOfCommencement', models.DateField(default=django.utils.timezone.now)),
                ('dateOfMaturity', models.DateField(default=django.utils.timezone.now)),
                ('expiryType', models.CharField(default='lifetime', max_length=20)),
                ('insuranceType', models.CharField(default='life', max_length=20)),
                ('confirmation', models.BooleanField(default=False)),
                ('aadhar', models.ImageField(upload_to='saved_images')),
            ],
        ),
    ]
