# Generated by Django 3.1.5 on 2021-04-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='saved_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
