# Generated by Django 3.1.5 on 2021-04-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insurances',
            new_name='Insurance',
        ),
    ]
