# Generated by Django 3.1.5 on 2021-04-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210429_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('policyID', models.CharField(db_column='policyID', max_length=30)),
                ('dateOfCommencement', models.DateTimeField(db_column='dateOfCommencement')),
                ('dateOfMaturity', models.DateField(db_column='dateOfMaturity')),
                ('expiryType', models.CharField(db_column='expiryType', max_length=30)),
                ('insuranceType', models.CharField(blank=True, db_column='insuranceType', max_length=30, null=True)),
                ('confirmation', models.BooleanField(default=False)),
                ('aadhar', models.ImageField(upload_to='saved_images')),
            ],
            options={
                'db_table': 'myapp_insurance',
            },
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
    ]
