# Generated by Django 3.1.5 on 2021-04-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210429_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurances',
            name='installmentAmount',
            field=models.FloatField(db_column='installmentAmount', default=0.0),
        ),
        migrations.AddField(
            model_name='insurances',
            name='maturityAmount',
            field=models.FloatField(db_column='maturityAmount', default=0.0),
        ),
    ]
